"""Initial migration

Revision ID: 0d7ba47a6567
Revises: 
Create Date: 2026-02-09 00:08:16.985813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d7ba47a6567'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('specialty_type', sa.String(length=100), nullable=True, comment='general, dental, obstetric, ophthalmic, etc.'),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Configuraciones personalizadas de la clínica'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_ruc'), 'clinics', ['ruc'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False, comment='DNI cifrado con Fernet — índice sobre hash'),
    sa.Column('dni_hash', sa.String(length=64), nullable=False, comment='SHA-256 de clinic_id+dni para búsquedas sin descifrar'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True, comment='masculino, femenino, otro'),
    sa.Column('phone', sa.String(length=255), nullable=True, comment='Cifrado con Fernet'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Cifrado con Fernet'),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True, comment='A+, A-, B+, B-, O+, O-, AB+, AB-'),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Lista de alergias: [{"name": "...", "severity": "..."}]'),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=255), nullable=True, comment='Cifrado con Fernet'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_patients_dni'), 'patients', ['dni'], unique=False)
    op.create_index(op.f('ix_patients_dni_hash'), 'patients', ['dni_hash'], unique=True)
    op.create_table('sync_device_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False, comment='Tipo de entidad: patient, appointment, record, etc.'),
    sa.Column('local_id', sa.String(length=36), nullable=False, comment='UUID generado en el dispositivo cliente'),
    sa.Column('server_id', sa.UUID(), nullable=False, comment='UUID real del registro en el servidor'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mapping_local', 'sync_device_mappings', ['clinic_id', 'device_id', 'entity', 'local_id'], unique=True)
    op.create_index('idx_mapping_server', 'sync_device_mappings', ['server_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'CLINIC_ADMIN', 'DOCTOR', 'RECEPTIONIST', name='userrole'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('cmp_number', sa.String(length=20), nullable=True, comment='Número de colegiatura médica (CMP)'),
    sa.Column('specialty', sa.String(length=100), nullable=True, comment='Especialidad médica'),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True, comment='TOTP secret cifrado'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clinic_id'), 'users', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'NO_SHOW', 'CANCELLED', name='appointmentstatus'), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False, comment='Tipo de servicio: consulta, control, procedimiento, etc.'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appointment_clinic_date', 'appointments', ['clinic_id', 'start_time'], unique=False)
    op.create_index('idx_appointment_doctor_date', 'appointments', ['doctor_id', 'start_time'], unique=False)
    op.create_index('idx_appointment_patient', 'appointments', ['patient_id', 'start_time'], unique=False)
    op.create_index('idx_appointment_status', 'appointments', ['clinic_id', 'status'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity', sa.String(length=50), nullable=False, comment='Nombre de la entidad: patient, appointment, record, etc.'),
    sa.Column('entity_id', sa.String(length=36), nullable=False, comment='UUID del registro afectado'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='create, update, delete, login, logout, etc.'),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot del registro antes del cambio'),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot del registro después del cambio'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_clinic_id'), 'audit_log', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity'), 'audit_log', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False, comment='0=Lunes, 1=Martes, 2=Miércoles, 3=Jueves, 4=Viernes, 5=Sábado, 6=Domingo'),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False, comment='Duración de cada slot de cita en minutos'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_clinic', 'doctor_schedules', ['clinic_id', 'is_active'], unique=False)
    op.create_index('idx_schedule_doctor_day', 'doctor_schedules', ['doctor_id', 'day_of_week'], unique=False)
    op.create_table('sync_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False, comment='Identificador único del dispositivo que envía el batch'),
    sa.Column('operations', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array de operaciones: [{entity, action, local_id, data, timestamp}]'),
    sa.Column('operation_count', sa.Integer(), nullable=False, comment='Cantidad de operaciones en el batch'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Resultado del procesamiento: {applied, conflicts, errors}'),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='Momento en que se terminó de procesar el batch'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_queue_clinic_status', 'sync_queue', ['clinic_id', 'status'], unique=False)
    op.create_index('idx_sync_queue_device', 'sync_queue', ['device_id', 'created_at'], unique=False)
    op.create_index('idx_sync_queue_user', 'sync_queue', ['user_id', 'created_at'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True, comment='Cita asociada (opcional)'),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('tipo_comprobante', sa.Enum('FACTURA', 'BOLETA', 'NOTA_CREDITO', 'NOTA_DEBITO', name='tipocomprobante'), nullable=False),
    sa.Column('serie', sa.String(length=4), nullable=False, comment='Serie: F001 (factura), B001 (boleta)'),
    sa.Column('correlativo', sa.Integer(), nullable=False, comment='Número correlativo autogenerado'),
    sa.Column('cliente_tipo_doc', sa.String(length=1), nullable=False, comment='Tipo documento: 1=DNI, 6=RUC, 0=Sin doc'),
    sa.Column('cliente_numero_doc', sa.String(length=15), nullable=False, comment='Número de documento del cliente'),
    sa.Column('cliente_denominacion', sa.String(length=200), nullable=False, comment='Nombre o razón social del cliente'),
    sa.Column('cliente_direccion', sa.String(length=500), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False, comment='Moneda: PEN (soles), USD (dólares)'),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False, comment='Subtotal sin IGV'),
    sa.Column('igv', sa.Numeric(precision=12, scale=2), nullable=False, comment='IGV (18%)'),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total con IGV'),
    sa.Column('forma_pago', sa.Enum('CONTADO', 'CREDITO', name='formapago'), nullable=False),
    sa.Column('sunat_status', sa.Enum('PENDING', 'QUEUED', 'EMITTED', 'ACCEPTED', 'REJECTED', 'VOIDED', 'ERROR', name='sunatstatus'), nullable=False),
    sa.Column('nubefact_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Respuesta completa de NubeFact API'),
    sa.Column('sunat_error_message', sa.Text(), nullable=True, comment='Mensaje de error de SUNAT si fue rechazado'),
    sa.Column('pdf_url', sa.String(length=500), nullable=True, comment='URL del PDF generado por NubeFact'),
    sa.Column('xml_url', sa.String(length=500), nullable=True, comment='URL del XML firmado'),
    sa.Column('cdr_url', sa.String(length=500), nullable=True, comment='URL del CDR (constancia de recepción)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('voided_reason', sa.String(length=500), nullable=True, comment='Motivo de anulación'),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de emisión'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoice_clinic_status', 'invoices', ['clinic_id', 'sunat_status'], unique=False)
    op.create_index('idx_invoice_issued', 'invoices', ['clinic_id', 'issued_at'], unique=False)
    op.create_index('idx_invoice_patient', 'invoices', ['clinic_id', 'patient_id'], unique=False)
    op.create_index('idx_invoice_serie_corr', 'invoices', ['clinic_id', 'serie', 'correlativo'], unique=True)
    op.create_table('medical_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True, comment='Cita asociada (opcional)'),
    sa.Column('record_type', sa.Enum('CONSULTATION', 'CONTROL', 'EMERGENCY', 'PROCEDURE', 'DENTAL', 'PRENATAL', 'OPHTHALMIC', 'LAB_RESULT', 'IMAGING', 'NOTE', name='recordtype'), nullable=False),
    sa.Column('cie10_codes', postgresql.ARRAY(sa.String(length=10)), nullable=True, comment="Códigos CIE-10 de diagnósticos: ['J06.9', 'R50.9']"),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Contenido clínico flexible: motivo, examen, diagnóstico, plan, etc.'),
    sa.Column('specialty_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Datos específicos de especialidad (odontograma, prenatal, etc.)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp de firma. Una vez firmado, el registro es INMUTABLE'),
    sa.Column('signed_by', sa.UUID(), nullable=True, comment='Doctor que firmó el registro'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_record_clinic_patient', 'medical_records', ['clinic_id', 'patient_id'], unique=False)
    op.create_index('idx_record_created', 'medical_records', ['clinic_id', 'created_at'], unique=False)
    op.create_index('idx_record_doctor', 'medical_records', ['clinic_id', 'doctor_id'], unique=False)
    op.create_index('idx_record_type', 'medical_records', ['clinic_id', 'record_type'], unique=False)
    op.create_table('dental_charts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=True, comment='Registro médico asociado (opcional)'),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('tooth_number', sa.SmallInteger(), nullable=False, comment='Número FDI: 11-18, 21-28, 31-38, 41-48 (adulto) / 51-55, 61-65, 71-75, 81-85 (deciduo)'),
    sa.Column('surfaces', postgresql.ARRAY(sa.String(length=2)), nullable=True, comment="Superficies afectadas: ['V','O','M','D','L']"),
    sa.Column('condition', sa.Enum('HEALTHY', 'CARIES', 'FILLED', 'EXTRACTED', 'MISSING', 'CROWN', 'BRIDGE', 'IMPLANT', 'ROOT_CANAL', 'FRACTURE', 'SEALANT', 'TEMPORARY', name='toothcondition'), nullable=False),
    sa.Column('treatment', sa.String(length=200), nullable=True, comment='Tratamiento realizado'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dental_clinic_patient', 'dental_charts', ['clinic_id', 'patient_id'], unique=False)
    op.create_index('idx_dental_patient_tooth', 'dental_charts', ['patient_id', 'tooth_number'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('unit_code', sa.String(length=5), nullable=False, comment='Código SUNAT de unidad de medida: ZZ=servicio, NIU=unidad'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Precio unitario sin IGV'),
    sa.Column('igv_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='IGV del ítem'),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total del ítem con IGV'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ophthalmic_exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=True, comment='Registro médico asociado (opcional)'),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('eye', sa.Enum('OD', 'OS', name='eyeside'), nullable=False),
    sa.Column('visual_acuity_uncorrected', sa.String(length=20), nullable=True, comment='AV sin corrección: 20/20, 20/40, etc.'),
    sa.Column('visual_acuity_corrected', sa.String(length=20), nullable=True, comment='AV con corrección: 20/20, 20/40, etc.'),
    sa.Column('sphere', sa.Float(), nullable=True, comment='Esfera (dioptrías): -20.00 a +20.00'),
    sa.Column('cylinder', sa.Float(), nullable=True, comment='Cilindro (dioptrías): -10.00 a +10.00'),
    sa.Column('axis', sa.Integer(), nullable=True, comment='Eje (grados): 0 a 180'),
    sa.Column('addition', sa.Float(), nullable=True, comment='Adición para presbicia: +0.50 a +4.00'),
    sa.Column('iop', sa.Float(), nullable=True, comment='Presión intraocular (mmHg): normal 10-21'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Campos adicionales: fondo de ojo, biomicroscopía, campimetría, etc.'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ophthalmic_eye', 'ophthalmic_exams', ['patient_id', 'eye'], unique=False)
    op.create_index('idx_ophthalmic_patient', 'ophthalmic_exams', ['clinic_id', 'patient_id'], unique=False)
    op.create_table('prenatal_visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=True, comment='Registro médico asociado (opcional)'),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('gestational_week', sa.SmallInteger(), nullable=False, comment='Semana de gestación al momento del control'),
    sa.Column('weight', sa.Float(), nullable=True, comment='Peso en kg'),
    sa.Column('blood_pressure_systolic', sa.SmallInteger(), nullable=True, comment='Presión arterial sistólica (mmHg)'),
    sa.Column('blood_pressure_diastolic', sa.SmallInteger(), nullable=True, comment='Presión arterial diastólica (mmHg)'),
    sa.Column('uterine_height', sa.Float(), nullable=True, comment='Altura uterina en cm'),
    sa.Column('fetal_heart_rate', sa.SmallInteger(), nullable=True, comment='Frecuencia cardíaca fetal (lpm)'),
    sa.Column('presentation', sa.String(length=50), nullable=True, comment='Presentación fetal: cefálica, podálica, transversa'),
    sa.Column('fetal_movements', sa.String(length=50), nullable=True, comment='Movimientos fetales: positivo, negativo, disminuido'),
    sa.Column('edema', sa.String(length=50), nullable=True, comment='Edema: ausente, leve, moderado, severo'),
    sa.Column('labs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Laboratorios: hemoglobina, glucosa, orina, VIH, RPR, grupo sanguíneo, etc.'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_appointment_notes', sa.String(length=500), nullable=True, comment='Indicaciones para próxima cita'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prenatal_patient', 'prenatal_visits', ['clinic_id', 'patient_id'], unique=False)
    op.create_index('idx_prenatal_week', 'prenatal_visits', ['patient_id', 'gestational_week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prenatal_week', table_name='prenatal_visits')
    op.drop_index('idx_prenatal_patient', table_name='prenatal_visits')
    op.drop_table('prenatal_visits')
    op.drop_index('idx_ophthalmic_patient', table_name='ophthalmic_exams')
    op.drop_index('idx_ophthalmic_eye', table_name='ophthalmic_exams')
    op.drop_table('ophthalmic_exams')
    op.drop_table('invoice_items')
    op.drop_index('idx_dental_patient_tooth', table_name='dental_charts')
    op.drop_index('idx_dental_clinic_patient', table_name='dental_charts')
    op.drop_table('dental_charts')
    op.drop_index('idx_record_type', table_name='medical_records')
    op.drop_index('idx_record_doctor', table_name='medical_records')
    op.drop_index('idx_record_created', table_name='medical_records')
    op.drop_index('idx_record_clinic_patient', table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index('idx_invoice_serie_corr', table_name='invoices')
    op.drop_index('idx_invoice_patient', table_name='invoices')
    op.drop_index('idx_invoice_issued', table_name='invoices')
    op.drop_index('idx_invoice_clinic_status', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_sync_queue_user', table_name='sync_queue')
    op.drop_index('idx_sync_queue_device', table_name='sync_queue')
    op.drop_index('idx_sync_queue_clinic_status', table_name='sync_queue')
    op.drop_table('sync_queue')
    op.drop_index('idx_schedule_doctor_day', table_name='doctor_schedules')
    op.drop_index('idx_schedule_clinic', table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_clinic_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_appointment_status', table_name='appointments')
    op.drop_index('idx_appointment_patient', table_name='appointments')
    op.drop_index('idx_appointment_doctor_date', table_name='appointments')
    op.drop_index('idx_appointment_clinic_date', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clinic_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_mapping_server', table_name='sync_device_mappings')
    op.drop_index('idx_mapping_local', table_name='sync_device_mappings')
    op.drop_table('sync_device_mappings')
    op.drop_index(op.f('ix_patients_dni_hash'), table_name='patients')
    op.drop_index(op.f('ix_patients_dni'), table_name='patients')
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_clinics_ruc'), table_name='clinics')
    op.drop_table('clinics')
    # ### end Alembic commands ###
